# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: azuresecrets

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: AzureCAT
    scriptLocation: inlineScript
    inlineScript: |
     mkdir .test-output
     npm run test-reporter
    failOnStandardError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results results.xml'
  inputs:
    testResultsFiles: results.xml
    searchFolder: '$(System.DefaultWorkingDirectory)/.test-output'
    testRunTitle: 'Unit Tests'

- task: tsuyoshiushio.shell-exec.shellexec.shellexec@0
  displayName: 'Create Distribution'
  inputs:
    code: |
     mkdir -p dist/templates
     cp azuredeploy.json dist/templates
     cp azuredeploy.parameters.json dist/templates

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/arm/dist'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**\*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'